### ISSUE TITLE
What is the purpose of dina-collections-api?

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/dina-collections#17]
This project contains a nodejs project called dina-collections-api. I was wondering what is its purpose and its link with https://github.com/DINA-Web/collections ?

**Comment by antonoberg** [comment]
Hi there! This is the new monorepo that will contain the api, schema and the ui (Its a monorepo but the api will be deployed as different services). Next week we will archive collections, dina-collections-ui and some other repos that now are included here. 

As you pointed out the project contains a nodejs project and that is our new backend. If you are interested I can give you some more details about the future plan for this repository.
